openapi: 3.0.0
info:
  title: GameTalk OpenAPI Specification
  description: >
    The GameTalk OpenAPI Specification provides a detailed framework for integrating game data with ChatGPT. This specification outlines the API endpoints, request and response formats, authentication methods, and data models required for seamless communication between game applications and the GameTalk platform. By adhering to this specification, developers can ensure robust and standardized integration, enabling real-time, intelligent conversations based on in-game events and player data.
  version: "1.0"

servers:
  - url: https://{{url}}/v1

security:
  - basicAuth: []  # Apply Basic Authentication to all operations

paths:
  /game-insights:
    post:
      tags:
        - gameinsights
      summary: Create Game Insights
      description: |
        This endpoint processes game data and returns an analysis based on the behaviors observed in the game.

        **Example `curl` command for creating game insights:**
        ```
        curl -u username:password -H "Content-Type: application/json" -d '[
          { "groupname": "YRLN", "name": "Idag", "count": 153 },
          { "groupname": "DIL", "name": "Idag", "count": 132 }
        ]' -X POST https://{{url}}/v1/game-insights
        ```
      operationId: createGameInsights
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/GameInsight'
      responses:
        '201':
          description: Game insights created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameInsightResponse'
        '400':
          description: Bad Request - The request was unacceptable, often due to missing a required parameter or malformed syntax.
        '422':
          description: Unprocessable Entity - The request is well-formed but contains validation errors.

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

  schemas:
    GameInsight:
      type: object
      required:
        - groupname
        - name
        - count
      properties:
        groupname:
          type: string
          example: "YRLN"
          description: "The name of the group (mandatory)"
        name:
          type: string
          example: "Idag"
          description: "The name of the behavior (mandatory)"
        count:
          type: integer
          example: 153
          description: "The count of the behavior (mandatory)"

    GameInsightResponse:
      type: object
      properties:
        status:
          type: string
          example: "success"
          description: "The status of the response"
        action:
          type: string
          example: "created"
          description: "The action taken by the API"
        data:
          type: object
          properties:
            result:
              type: string
              example: "Team YRLN, you guys are leading the pack with 'Idag' behavior..."
              description: "The detailed analysis and feedback for the game insights"

    ResponseStatus:
      type: string
      example: "success"
      description: "The status of the API response"

    ResponseActions:
      type: string
      example: "created"
      description: "The action that was performed by the API"

